// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroTrack.Data;

#nullable disable

namespace NeuroTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250616191336_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeuroTrack.Models.Moment", b =>
                {
                    b.Property<int>("MomentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MomentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("EstimatedDuration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("MomentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MomentId");

                    b.ToTable("Moments");
                });
#pragma warning restore 612, 618
        }
    }
}
